ARG GCC_V=14

FROM debian:trixie-slim AS llvm_builder

ARG GCC_V
ENV GCC_V=$GCC_V
ENV CCACHE_DIR=/ccache

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  binutils \
  binutils-dev \
  ccache \
  cmake \
  gcc-${GCC_V} \
  gcc-${GCC_V}-plugin-dev \
  g++-${GCC_V} \
  git \
  ninja-build \
  python3

RUN git clone --depth 1 --branch "llvmorg-21.1.8" https://github.com/llvm/llvm-project.git

# Build clang and runtimes
RUN --mount=type=cache,target=/ccache/ \
    cmake -S /llvm-project/llvm \
          -G Ninja \
          -B /llvm-project/build/ \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=gcc-${GCC_V} \
          -DCMAKE_CXX_COMPILER=g++-${GCC_V} \
          -DCMAKE_INSTALL_PREFIX=/llvm_build \
          -DLLVM_BINUTILS_INCDIR=/usr/include \
          -DLLVM_CCACHE_BUILD=ON \
          -DLLVM_ENABLE_PROJECTS="clang" \
          -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" \
          -DLLVM_TARGETS_TO_BUILD=Native && \
    ninja -C /llvm-project/build/ "-j$(nproc)" install/strip

# Build a memory sanitizer instrumented libc++
RUN --mount=type=cache,target=/ccache/ \
    cmake -S /llvm-project/runtimes \
          -G Ninja \
          -B /libcxx_msan \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=/llvm_build/bin/clang \
          -DCMAKE_CXX_COMPILER=/llvm_build/bin/clang++ \
          -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
          -DLIBCXX_HARDENING_MODE=debug \
          -DLIBCXX_ABI_DEFINES="_LIBCPP_ABI_BOUNDED_ITERATORS;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_STD_ARRAY;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_STRING;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_VECTOR;_LIBCPP_ABI_BOUNDED_UNIQUE_PTR" \
          -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF \
          -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;libunwind' \
          -DLLVM_TARGETS_TO_BUILD=Native \
          -DLLVM_USE_SANITIZER=MemoryWithOrigins && \
    ninja -C /libcxx_msan "-j$(nproc)"

FROM rust:1.91.1-slim-trixie AS rust_builder

WORKDIR /fuzzor
COPY . .

RUN cargo install rustfilt
RUN cargo install --verbose --path infra/builder
RUN cargo install --verbose --path infra/reproducer
RUN cargo install --verbose --path infra/ensemble-fuzz
RUN cargo install --verbose --path infra/coverage-reporter
RUN cargo install --verbose --path infra/minimizer
RUN cargo install --verbose --path infra/fuzzer

FROM debian:trixie-slim

ARG GCC_V
ENV GCC_V=$GCC_V

COPY --from=llvm_builder /llvm_build* /usr/
COPY --from=llvm_builder /libcxx_msan /libcxx_msan
COPY --from=rust_builder /fuzzor/infra/toolchains /toolchains

# Be selective, so we don't copy rustc/cargo etc, which may interfere
# with other builds later, i.e rust-lightning
COPY --from=rust_builder /usr/local/cargo/bin/builder \
                         /usr/local/cargo/bin/coverage-reporter \
                         /usr/local/cargo/bin/ensemble-fuzz \
                         /usr/local/cargo/bin/fuzzer \
                         /usr/local/cargo/bin/minimizer \
                         /usr/local/cargo/bin/reproducer \
                         /usr/local/cargo/bin/semsam* \
                         /usr/local/bin/

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
  autotools-dev \
  automake \
  binutils-dev \
  build-essential \
  ccache \
  cmake \
  curl \
  cpio \
  gcc-${GCC_V}-arm-linux-gnueabihf \
  g++-${GCC_V}-arm-linux-gnueabihf \
  gcc-${GCC_V}-x86-64-linux-gnu \
  g++-${GCC_V}-x86-64-linux-gnu \
  gcc-${GCC_V}-plugin-dev \
  git \
  libtool \
  libunwind-dev \
  libz3-dev \
  linux-perf \
  ninja-build \
  openssh-client \
  pkg-config \
  pax-utils \
  python3 \
  python3-msgpack \
  python3-jinja2 \
  python3-venv \
  rsync

# Build & force mold usage
RUN git clone https://github.com/rui314/mold.git --depth 1 --branch v2.41.0 && \
    cmake -G Ninja -B /mold/build -S mold -DCMAKE_BUILD_TYPE=Release && \
    ninja -C /mold/build/ "-j$(nproc)" install/strip && \
    rm -rf /mold && \
    rm -rf $(which ld) && ln -s $(which mold) /usr/bin/ld

RUN git clone https://github.com/google/honggfuzz.git && \
    make install -C honggfuzz && \
    rm -rf honggfuzz

# Clone AFLplusplus and build
RUN git clone --branch stable https://github.com/AFLplusplus/AFLplusplus && \
    make -C AFLplusplus PERFORMANCE=1 \
                        LLVM_CONFIG=llvm-config \
                        # actually mold
                        AFL_REAL_LD=/usr/bin/ld \
                        -j$(nproc) && \
    make -C AFLplusplus install

# Install FlameGraph
RUN git clone --depth 1 https://github.com/brendangregg/FlameGraph
ENV FLAMEGRAPH_REPO=/FlameGraph

WORKDIR /workdir
RUN mkdir --parents workspace/corpus
RUN mkdir --parents workspace/min_corpus
RUN mkdir --parents workspace/initial_solutions

# Location for the harness binaries
ENV FUZZOR_HARNESSES=/workdir/out

# Some afl++ options
ENV AFL_FUZZER_STATS_UPDATE_INTERVAL=10
ENV AFL_NO_CRASH_README=1
ENV AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
ENV AFL_SKIP_CPUFREQ=1
ENV AFL_HANG_TMOUT=60000

ENV MSAN_LIBCXX_PATH=/libcxx_msan

ENV LLVM_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"
ENV UBSAN_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"
ENV ASAN_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"
ENV MSAN_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"
ENV TSAN_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"

RUN touch ubsan_suppressions tsan_suppressions
ENV ASAN_OPTIONS="strict_string_checks=1:detect_invalid_pointer_pairs=2:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:abort_on_error=1:exitcode=75"
ENV UBSAN_OPTIONS="suppressions=/workdir/ubsan_suppressions:print_stacktrace=1:halt_on_error=1:abort_on_error=1:report_error_type=1:silence_unsigned_overflow=1:exitcode=76"
ENV TSAN_OPTIONS="suppressions=/workdir/tsan_suppressions:halt_on_error=1:abort_on_error=1:exitcode=79"

# Enable env_logger by default with level info
ENV RUST_LOG=trace
