ARG BASE_IMAGE=fuzzor-base
FROM ${BASE_IMAGE}

# Install rust
ENV PATH="/root/.cargo/bin:${PATH}"
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y \
    && rustup install nightly

ARG OWNER=lightningdevkit
ARG REPO=rust-lightning
ARG BRANCH=main
ARG REVISION=

RUN git clone --depth 1 --branch $BRANCH https://github.com/$OWNER/$REPO.git
RUN cd $REPO/fuzz && cargo update && cargo install --force cargo-fuzz

COPY ./config.yaml .
COPY ./build.sh .

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/workdir/rust-lightning/fuzz/target \
    builder $PWD/config.yaml $PWD/build.sh $FUZZOR_HARNESSES
