name: Images

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-base-image:
    runs-on: runs-on=${{ github.run_id }}/runner=32cpu-linux-x64/extras=ecr-cache/volume=120gb
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - name: Build and push base fuzzor image to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/Dockerfile.base
          build-args: FUZZOR_CI=1
          push: true
          tags: ${{ env.RUNS_ON_ECR_CACHE }}:fuzzor-base-${{ github.run_id }}
          cache-from: type=registry,ref=${{ env.RUNS_ON_ECR_CACHE }}:fuzzor-base-cache
          cache-to: type=registry,ref=${{ env.RUNS_ON_ECR_CACHE }}:fuzzor-base-cache,mode=max

  build-project-images:
    needs: [build-base-image]
    runs-on: runs-on=${{ github.run_id }}/runner=8cpu-linux-x64/extras=ecr-cache/volume=120gb
    strategy:
      fail-fast: false
      matrix:
        project:
          - bitcoin
          - lnd
          - core-lightning
          - rust-lightning
          - rust-psbt
          - openssl
          - secp256k1
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.project }} fuzzor image
        uses: docker/build-push-action@v6
        with:
          context: projects/${{ matrix.project }}
          load: true
          tags: fuzzor-${{ matrix.project }}:latest
          build-args: BASE_IMAGE=${{ env.RUNS_ON_ECR_CACHE }}:fuzzor-base-${{ github.run_id }}
          cache-from: type=registry,ref=${{ env.RUNS_ON_ECR_CACHE }}:fuzzor-${{ matrix.project }}-cache
          cache-to: type=registry,ref=${{ env.RUNS_ON_ECR_CACHE }}:fuzzor-${{ matrix.project }}-cache,mode=max
